// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQickIN_H47CS5kzYIb-hJbBKs4De4icg',
    appId: '1:858214490721:web:cdb9fa56900864c90f8020',
    messagingSenderId: '858214490721',
    projectId: 'ulisync-e4683',
    authDomain: 'ulisync-e4683.firebaseapp.com',
    storageBucket: 'ulisync-e4683.appspot.com',
    measurementId: 'G-QJFF0J9XJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBRzwhUVW7qUzoAWbJWdOmppSNXEM_aE0',
    appId: '1:858214490721:android:e007f80bced3e4e10f8020',
    messagingSenderId: '858214490721',
    projectId: 'ulisync-e4683',
    storageBucket: 'ulisync-e4683.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN3mQ5--7A_Zs1a09JJNv_CRIVgmrpS1w',
    appId: '1:858214490721:ios:50e3ae61184241040f8020',
    messagingSenderId: '858214490721',
    projectId: 'ulisync-e4683',
    storageBucket: 'ulisync-e4683.appspot.com',
    iosBundleId: 'com.example.ulisYnc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN3mQ5--7A_Zs1a09JJNv_CRIVgmrpS1w',
    appId: '1:858214490721:ios:50e3ae61184241040f8020',
    messagingSenderId: '858214490721',
    projectId: 'ulisync-e4683',
    storageBucket: 'ulisync-e4683.appspot.com',
    iosBundleId: 'com.example.ulisYnc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQickIN_H47CS5kzYIb-hJbBKs4De4icg',
    appId: '1:858214490721:web:b7c8c772f8758f260f8020',
    messagingSenderId: '858214490721',
    projectId: 'ulisync-e4683',
    authDomain: 'ulisync-e4683.firebaseapp.com',
    storageBucket: 'ulisync-e4683.appspot.com',
    measurementId: 'G-0S9Q9WNBRZ',
  );
}
